// @vitest-environment jsdom
/**
 * Feature: pinpoint-app, Property 9: DOM selector round-trip
 *
 * For any DOM element in a page that has a unique CSS selector, computing the
 * CSS selector for that element and then resolving the computed selector on the
 * same page shall return the original DOM element. The resolved element shall
 * have the same tagName, textContent, and position in the DOM tree as the original.
 *
 * **Validates: Requirements 14.1, 14.4**
 *
 * We test the pure functions computeCssSelector and computeXPath against a
 * jsdom-simulated DOM tree generated by fast-check.
 */
import { describe, it, expect, beforeEach } from 'vitest';
import fc from 'fast-check';
import { computeCssSelector, computeXPath } from '../../lib/DOMTargetResolver';

// We need a minimal CSS.escape polyfill for jsdom
if (typeof CSS === 'undefined' || !CSS.escape) {
  (globalThis as any).CSS = {
    escape: (s: string) => s.replace(/([^\w-])/g, '\\$1'),
  };
}

/** Build a simple DOM tree and return all leaf elements. */
function buildDomTree(
  doc: Document,
  depth: number,
  childrenPerLevel: number[],
  tagNames: string[]
): Element[] {
  const root = doc.documentElement.querySelector('body')!;
  const leaves: Element[] = [];

  function build(parent: Element, level: number) {
    if (level >= depth) {
      leaves.push(parent);
      return;
    }
    const count = childrenPerLevel[level % childrenPerLevel.length];
    for (let i = 0; i < count; i++) {
      const tag = tagNames[(level * count + i) % tagNames.length];
      const el = doc.createElement(tag);
      el.textContent = `text-${level}-${i}`;
      parent.appendChild(el);
      build(el, level + 1);
    }
  }

  build(root, 0);
  return leaves;
}

describe('Property 9: DOM selector round-trip', () => {
  beforeEach(() => {
    document.body.innerHTML = '';
  });

  it('CSS selector round-trip: computing then resolving returns the original element', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 3 }), // depth
        fc.array(fc.integer({ min: 1, max: 3 }), { minLength: 1, maxLength: 3 }), // children per level
        fc.array(
          fc.constantFrom('div', 'span', 'p', 'section', 'article', 'main', 'nav', 'ul', 'li'),
          { minLength: 1, maxLength: 5 }
        ), // tag names
        (depth, childrenPerLevel, tagNames) => {
          // Reset DOM
          document.body.innerHTML = '';

          const leaves = buildDomTree(document, depth, childrenPerLevel, tagNames);
          if (leaves.length === 0) return; // skip trivial case

          // Pick a random leaf to test
          for (const leaf of leaves) {
            const selector = computeCssSelector(leaf);
            const resolved = document.querySelector(selector);

            // Round-trip: resolved element should be the original
            expect(resolved).toBe(leaf);
            expect(resolved?.tagName).toBe(leaf.tagName);
            expect(resolved?.textContent).toBe(leaf.textContent);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('XPath round-trip: computing then resolving returns the original element', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 3 }),
        fc.array(fc.integer({ min: 1, max: 3 }), { minLength: 1, maxLength: 3 }),
        fc.array(
          fc.constantFrom('div', 'span', 'p', 'section', 'article'),
          { minLength: 1, maxLength: 4 }
        ),
        (depth, childrenPerLevel, tagNames) => {
          document.body.innerHTML = '';

          const leaves = buildDomTree(document, depth, childrenPerLevel, tagNames);
          if (leaves.length === 0) return;

          for (const leaf of leaves) {
            const xpath = computeXPath(leaf);
            const result = document.evaluate(
              xpath,
              document,
              null,
              XPathResult.FIRST_ORDERED_NODE_TYPE,
              null
            );
            const resolved = result.singleNodeValue;

            expect(resolved).toBe(leaf);
            expect((resolved as Element)?.tagName).toBe(leaf.tagName);
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});
